import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const Inter = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={Inter.className}>
        {children}
      </body>
    </html>
  );
}
